CREATE DATABASE IF NOT EXISTS `users`;
CREATE USER 'user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
CREATE USER 'user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'localhost' WITH GRANT OPTION;
USE `users`
CREATE TABLE IF NOT EXISTS accounts
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    mail VARCHAR(20),
    password VARCHAR(20)
);
FLUSH PRIVILEGES;